version: '3.8'

services:
  trade-dashboard:
    build: 
      context: https://github.com/sanpconsulting/trade-dashboard.git#main
    container_name: trade-dashboard
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    # Cette ligne permet au conteneur de résoudre 'host.docker.internal' vers l'IP de votre machine physique
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
